name: Test if build passes

# We will trigger this only on the master branch for now to save CI time
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-pass-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Sync submodules
        run: git submodule update --init
      - name: install package dependencies
        run: sudo scripts/install/packages/mint.sh
      - name: install rust
        run: scripts/install/rust-linux.sh
      - name: configure
        run: ./config.sh default
      - name: Build x86_64
        run: source $HOME/.cargo/env && python3 smeltfile.py iso
